version: '3.8'

services:
  # Production service
  openrobotics-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openrobotics-lab-prod
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - openrobotics-network

  # Development service
  openrobotics-lab-dev:
    image: node:18-alpine
    container_name: openrobotics-lab-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped
    networks:
      - openrobotics-network
    profiles:
      - dev

networks:
  openrobotics-network:
    driver: bridge